name: Daily UPSC Current Affairs

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg --fix-missing
    
    - name: Install Python dependencies
      run: |
        pip install feedparser requests pillow azure-cognitiveservices-speech python-dotenv beautifulsoup4 openai
        pip install google-auth-oauthlib google-auth-httplib2 google-api-python-client
    
    - name: Create .env
      run: |
        echo "AZURE_SPEECH_KEY=${{ secrets.AZURE_SPEECH_KEY }}" >> .env
        echo "AZURE_SPEECH_REGION=${{ secrets.AZURE_SPEECH_REGION }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> .env
    
    - name: Create YouTube credentials
      run: |
        mkdir -p config
        echo '${{ secrets.YOUTUBE_OAUTH }}' > config/youtube-oauth.json
        echo '${{ secrets.YOUTUBE_TOKEN }}' | base64 -d > youtube-token.pickle
    
    - name: Run automation
      run: python3 scripts/run_upsc_daily.py
    
    - name: Upload to YouTube
      run: python3 scripts/upload_youtube_auto.py
    
    - name: Clean up
      run: rm -rf output/upsc/chunks youtube-token.pickle
